# Generated by Django 4.2.2 on 2023-07-03 18:52

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('news_id', models.BigIntegerField(null=True)),
                ('news_type', models.CharField(max_length=200)),
                ('by', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('time', models.BigIntegerField(default=1688410368.644223, null=True)),
                ('text', models.TextField(null=True)),
                ('dead', models.BooleanField(default=False)),
                ('parent', models.BigIntegerField(null=True)),
                ('poll', models.BigIntegerField(null=True)),
                ('kids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(null=True), default=list, size=None)),
                ('url', models.TextField(null=True, validators=[django.core.validators.URLValidator()])),
                ('score', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('part', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(blank=True, null=True), default=list, size=None)),
                ('descendants', models.BigIntegerField(null=True)),
                ('is_hacker_news', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
    ]
