# Generated by Django 4.2.2 on 2023-07-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_alter_news_score_alter_news_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.BigIntegerField(default=1688766538.867885, null=True),
        ),
    ]
